Nop.Plugin.Payments.Yuansfer/Controllers/YuansferPaymentController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Payments.Yuansfer.Models;
using Nop.Plugin.Payments.Yuansfer.Services;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.Yuansfer.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class YuansferPaymentController : BasePaymentController
    {
        #region Fields

        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IWorkContext _workContext;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly YuansferApi _yuansferApi;

        #endregion

        #region Ctor

        public YuansferPaymentController(ICustomerService customerService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext,
            IWorkContext workContext,
            ShoppingCartSettings shoppingCartSettings,
            YuansferApi yuansferApi)
        {
            _customerService = customerService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
            _workContext = workContext;
            _shoppingCartSettings = shoppingCartSettings;
            _yuansferApi = yuansferApi;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var yuansferPaymentSettings = await _settingService.LoadSettingAsync<YuansferPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                ActiveStoreScopeConfiguration = storeScope,
                BaseApiUrl = yuansferPaymentSettings.BaseApiUrl,
                MerchantId = yuansferPaymentSettings.MerchantId,
                StoreId = yuansferPaymentSettings.StoreId,
                ApiToken = yuansferPaymentSettings.ApiToken,
                PaymentChannels = yuansferPaymentSettings.PaymentChannels,
                AdditionalFee = yuansferPaymentSettings.AdditionalFee,
                AdditionalFeePercentage = yuansferPaymentSettings.AdditionalFeePercentage,
                AvailablePaymentChannels = Defaults.AvailablePaymentChannels
            };

            if (storeScope > 0)
            {
                model.BaseApiUrl_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.BaseApiUrl, storeScope);
                model.MerchantId_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.MerchantId, storeScope);
                model.StoreId_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.StoreId, storeScope);
                model.ApiToken_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.ApiToken, storeScope);
                model.PaymentChannels_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.PaymentChannels, storeScope);
                model.AdditionalFee_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = await _settingService.SettingExistsAsync(yuansferPaymentSettings, x => x.AdditionalFeePercentage, storeScope);
            }

            //prices and total aren't rounded, so display warning
            if (!_shoppingCartSettings.RoundPricesDuringCalculation)
            {
                var url = Url.Action("AllSettings", "Setting", new { settingName = nameof(ShoppingCartSettings.RoundPricesDuringCalculation) });
                var warning = string.Format(await _localizationService.GetResourceAsync("Plugins.Payments.Yuansfer.RoundingWarning"), url);
                _notificationService.WarningNotification(warning, false);
            }

            return View("~/Plugins/Payments.Yuansfer/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var yuansferPaymentSettings = await _settingService.LoadSettingAsync<YuansferPaymentSettings>(storeScope);

            //save settings
            yuansferPaymentSettings.BaseApiUrl = model.BaseApiUrl;
            yuansferPaymentSettings.MerchantId = model.MerchantId;
            yuansferPaymentSettings.StoreId = model.StoreId;
            yuansferPaymentSettings.ApiToken = model.ApiToken;
            yuansferPaymentSettings.PaymentChannels = model.PaymentChannels.ToList();
            yuansferPaymentSettings.AdditionalFee = model.AdditionalFee;
            yuansferPaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */

            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.BaseApiUrl, model.BaseApiUrl_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.MerchantId, model.MerchantId_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.StoreId, model.StoreId_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.ApiToken, model.ApiToken_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.PaymentChannels, model.PaymentChannels_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(yuansferPaymentSettings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeScope, false);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("request-demo")]
        public async Task<IActionResult> RequestDemo(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            try
            {
                var customer = await _workContext.GetCurrentCustomerAsync();
                var fullName = await _customerService.GetCustomerFullNameAsync(customer);
                var request = new MerchantInfoRequest
                {
                    Email = model.MerchantEmail,
                    ClientName = fullName,
                    Plugin = Defaults.Api.UserAgent
                };
                var response = await _yuansferApi.RequestDemoAsync(request);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Plugins.Payments.Yuansfer.Fields.MerchantEmail.Success"));
            }
            catch (Exception exception)
            {
                await _notificationService.ErrorNotificationAsync(exception);
            }

            return await Configure();
        }

        #endregion
    }
}

Nop.Plugin.Payments.Yuansfer/Views/Configure.cshtml
@model ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="YuansferPayment" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="MerchantEmail" />
                    </div>
                    <div class="col-md-9">
                        <div class="input-group">
                            <nop-editor asp-for="MerchantEmail" />
                            <div class="input-group-btn">
                                <input type="submit" name="request-demo" class="btn btn-info" value="@T("Plugins.Payments.Yuansfer.Fields.MerchantEmail.Button")" />
                            </div>
                        </div>
                        <span asp-validation-for="MerchantEmail"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-default">
            <div class="card-body">
                @Html.Raw(T("Plugins.Payments.Yuansfer.Instructions"))
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="BaseApiUrl_OverrideForStore" asp-input="BaseApiUrl" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="BaseApiUrl" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="BaseApiUrl" />
                        <span asp-validation-for="BaseApiUrl"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="MerchantId_OverrideForStore" asp-input="MerchantId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="StoreId_OverrideForStore" asp-input="StoreId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="StoreId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="StoreId" />
                        <span asp-validation-for="StoreId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ApiToken_OverrideForStore" asp-input="ApiToken" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ApiToken" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ApiToken" />
                        <span asp-validation-for="ApiToken"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PaymentChannels_OverrideForStore" asp-input="PaymentChannels" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PaymentChannels" />
                    </div>
                    <div class="col-md-9">
                        <select asp-for="PaymentChannels" asp-items="@Model.AvailablePaymentChannels"></select>
                        <span asp-validation-for="PaymentChannels"></span>
                        <script>
                            $(document).ready(function () {
                                var paymentChannelIdsInput = $("#@Html.IdFor(model => model.PaymentChannels)").kendoMultiSelect({
                                    select: function (e) {
                                        var current = this.value();
                                        if (this.dataSource.view()[e.item.index()].value === "0") {
                                            this.value("");
                                        }
                                        else if (current.indexOf("0") !== -1) {
                                            current = $.grep(current, function (value) {
                                                return value !== "0";
                                            });
                                            this.value(current);
                                        }
                                    },
                                    change: function (e) {
                                        if (this.value().length === 0)
                                            this.value(["0"]);
                                    },
                                    autoClose: false,
                                    filter: "contains"
                                }).data("kendoMultiSelect");
                            });
                        </script>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.Yuansfer/Views/PaymentInfo.cshtml
@model PaymentInfoModel

@{
    Layout = "";
}

@if (ViewData.ModelState.IsValid)
{
    <label asp-for="PaymentChannel">@T("Plugins.Payments.Yuansfer.PaymentChannel.Select")</label>
    <select asp-for="PaymentChannel" asp-items="@Model.AvailablePaymentChannels"></select>
}
else
{
    <script asp-location="Footer">
        $(document).ready(function () {
            var $nexStepBtn = $('.payment-info-next-step-button');
            if ($nexStepBtn) {
                $nexStepBtn.hide();
            }
        });
    </script>
}

@if (orderSettings.OnePageCheckoutEnabled)
{
    @NopHtml.GenerateInlineScripts(ResourceLocation.Footer)
}